object Versions {
    const val kotlin = "1.9.22"
    const val ktor = "2.3.8"
    const val kotlinxSerialization = "1.6.2"
    const val coroutines = "1.7.3"
    const val springBoot = "3.2.2"
    const val flowable = "6.8.0"
    const val fabricSdk = "2.2.15"
    const val logback = "1.4.14"
    const val exposed = "0.44.0"
    const val hikari = "5.1.0"
    const val postgres = "42.7.2"
    const val kafka = "3.6.1"
    const val minio = "8.5.2"
    const val ktorClient = ktor
}

object Deps {
    const val kotlinStdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${'$'}{Versions.kotlin}"
    const val kotlinReflect = "org.jetbrains.kotlin:kotlin-reflect:${'$'}{Versions.kotlin}"
    const val ktorServerCore = "io.ktor:ktor-server-core:${'$'}{Versions.ktor}"
    const val ktorServerNetty = "io.ktor:ktor-server-netty:${'$'}{Versions.ktor}"
    const val ktorServerContentNegotiation = "io.ktor:ktor-server-content-negotiation:${'$'}{Versions.ktor}"
    const val ktorSerializationJson = "io.ktor:ktor-serialization-kotlinx-json:${'$'}{Versions.ktor}"
    const val ktorServerAuth = "io.ktor:ktor-server-auth:${'$'}{Versions.ktor}"
    const val ktorServerAuthJwt = "io.ktor:ktor-server-auth-jwt:${'$'}{Versions.ktor}"
    const val ktorServerCallLogging = "io.ktor:ktor-server-call-logging:${'$'}{Versions.ktor}"
    const val ktorClientCore = "io.ktor:ktor-client-core:${'$'}{Versions.ktorClient}"
    const val ktorClientCio = "io.ktor:ktor-client-cio:${'$'}{Versions.ktorClient}"
    const val ktorClientContentNegotiation = "io.ktor:ktor-client-content-negotiation:${'$'}{Versions.ktorClient}"
    const val ktorClientAuth = "io.ktor:ktor-client-auth:${'$'}{Versions.ktorClient}"
    const val ktorClientLogging = "io.ktor:ktor-client-logging:${'$'}{Versions.ktorClient}"
    const val logbackClassic = "ch.qos.logback:logback-classic:${'$'}{Versions.logback}"
    const val kotlinxSerializationJson = "org.jetbrains.kotlinx:kotlinx-serialization-json:${'$'}{Versions.kotlinxSerialization}"
    const val exposedCore = "org.jetbrains.exposed:exposed-core:${'$'}{Versions.exposed}"
    const val exposedDao = "org.jetbrains.exposed:exposed-dao:${'$'}{Versions.exposed}"
    const val exposedJdbc = "org.jetbrains.exposed:exposed-jdbc:${'$'}{Versions.exposed}"
    const val exposedJavaTime = "org.jetbrains.exposed:exposed-java-time:${'$'}{Versions.exposed}"
    const val hikari = "com.zaxxer:HikariCP:${'$'}{Versions.hikari}"
    const val postgresDriver = "org.postgresql:postgresql:${'$'}{Versions.postgres}"
    const val kafkaClients = "org.apache.kafka:kafka-clients:${'$'}{Versions.kafka}"
    const val minio = "io.minio:minio:${'$'}{Versions.minio}"
    const val fabricGateway = "org.hyperledger.fabric:fabric-gateway-java:${'$'}{Versions.fabricSdk}"
    const val fabricSdk = "org.hyperledger.fabric-sdk-java:fabric-sdk-java:${'$'}{Versions.fabricSdk}"
    const val fabricProtos = "org.hyperledger.fabric:fabric-protos:${'$'}{Versions.fabricSdk}"
    const val flowableSpringBootStarter = "org.flowable:flowable-spring-boot-starter-process:${'$'}{Versions.flowable}"
    const val flowableDmn = "org.flowable:flowable-spring-boot-starter-dmn:${'$'}{Versions.flowable}"
    const val jacksonDatabind = "com.fasterxml.jackson.core:jackson-databind:2.16.1"
    const val jacksonKotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.16.1"
    const val micrometerRegistryPrometheus = "io.micrometer:micrometer-registry-prometheus:1.12.3"
    const val jwksRsa = "com.auth0:jwks-rsa:0.22.1"
}
